<?xml version="1.0"?>
<robot xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
       xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
       xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
       xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:property name="laserWidth" value="0.05"/> <!-- Width of the base -->
  <xacro:property name="laserLength" value="0.05"/> <!-- Length of the base -->
  <xacro:property name="laserHeight" value="0.07"/> <!-- Height -->

	<!-- Inlude Gazebo element -->
  <xacro:include filename="$(find mag_description)/urdf/sensors/hokuyo_laser.gazebo.xacro" />

  <xacro:macro name="hokuyo_laser" params="parent *origin topic">
    <link name="hokuyo_base" type="laser">
		  <visual>
		  	<origin xyz="0 0 -${laserHeight/2}" />
		    <geometry>
					<mesh filename="package://mag_description/meshes/hokuyo_laser.dae"/>
		    </geometry>
		  </visual>
		  
		  <collision>
		  	<origin xyz="0 0 -${laserHeight/2}" />
		    <geometry>
		      <box size="${laserWidth} ${laserLength} ${laserHeight}" />
		    </geometry>
		  </collision>
    
      <inertial>
		  	<origin xyz="0 0 -${laserHeight/4}" />
        <mass value="0.1" />
        <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001" />
      </inertial>
    </link>
    
    <joint name="hokuyo_joint" type="fixed">
      <parent link="${parent}"/>
      <child link="hokuyo_base"/>
      <axis xyz="0 1 0" />
      <insert_block name="origin" />
    </joint>

		<link name="hokuyo_link"/> <!-- Dummy link to correct the sensor in gazebo -->

		<joint name="laser_joint" type="fixed">
			<parent link="hokuyo_base"/>
			<child link="hokuyo_link"/>
			<axis xyz="0 1 0"/>
			<origin xyz="0 0 ${laserHeight/2-0.005}" rpy="0 0 0"/>
		</joint>
    
	  <!-- Gazebo elements -->
	  <xacro:hokuyo_laser_gazebo topic="${topic}" laserHeight="${laserHeight}"/>
  </xacro:macro>
  
</robot>
