<?xml version="1.0"?>
<robot xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
				xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
				xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
				xmlns:xacro="http://ros.org/wiki/xacro">

 <!-- <xacro:property name="imuWidth" value="0.0173"/> --> <!-- Width of the base -->
 <!-- <xacro:property name="imuLength" value="0.01585"/> --> <!-- Length of the base -->
  <xacro:property name="imuWidth" value="0.05"/> <!-- Width of the base -->
  <xacro:property name="imuLength" value="0.15"/> <!-- Length of the base -->
  <xacro:property name="imuHeight" value="0.01241"/> <!-- Height -->

	<!-- Include Gazebo element -->
	<xacro:include filename="$(find mag_description)/urdf/sensors/imu.gazebo.xacro" />

	<xacro:macro name="imu" params="parent link *origin topic">
		<link name="${link}">
		  <visual>
		    <origin xyz="0 0 ${imuHeight/2}"/>
		    <geometry>
		      <box size="${imuWidth} ${imuLength} ${imuHeight}" />
		    </geometry>
		  </visual>
		  
		  <collision>
		    <origin xyz="0 0 ${imuHeight/2}"/>
		    <geometry>
		      <box size="${imuWidth} ${imuLength} ${imuHeight}" />
		    </geometry>
		  </collision>
		  
			<inertial>
		    <origin xyz="0 0 ${imuHeight/2}"/>
				<mass value="0.01" />
				<inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001" />
			</inertial>
		</link>
		
		<joint name="imu_joint" type="fixed">
			<axis xyz="0 1 0" />
			<insert_block name="origin" />
			<parent link="${parent}"/>
			<child link="${link}"/>
		</joint>

		<!-- Gazebo element -->
		<xacro:imu_gazebo topic="${topic}" link="${link}"/>
	</xacro:macro>
	
</robot>
