magabot:
  # Publish all joint states -----------------------------------
  jointControl:
    type: joint_state_controller/JointStateController
    publish_rate: 80
  
  # Position Controllers ---------------------------------------
  leftControl:
    type: effort_controllers/JointPositionController
    joint: base_leftwheel
    pid: {p: 1.0, i: 0.1, d: 1.0}
  rightControl:
    type: effort_controllers/JointPositionController
    joint: base_rightwheel
    pid: {p: 1.0, i: 0.1, d: 1.0}
